name: Build and publish multi-arch docker image

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Hadolint Dockerfile Linter
        uses: hadolint/hadolint-action@f988afea3da57ee48710a9795b6bb677cc901183
        with:
          dockerfile: Dockerfile
          format: sarif
          output-file: hadolint-results.sarif

      - name: Upload analysis results to GitHub
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: hadolint-results.sarif
          wait-for-processing: true

      - name: Update Pull Request with Hadolint Report
        uses: actions/github-script@v6
        if: ${{ failure() }}
        with:
          script: |
            const output = `
            #### Hadolint: \`${{ steps.hadolint.outcome }}\`
            \`\`\`
            ${process.env.HADOLINT_RESULTS}
            \`\`\`
            `;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Kaniko build
        uses: aevea/action-kaniko@57fd639926c415a2fa4150ac72230eb5758ff48b
        with:
          image: awscli-kubectl
          registry: ghcr.io
          password: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.event.pull_request.head.sha }}

      # - name: Kaniko build
      #   uses: aevea/action-kaniko@57fd639926c415a2fa4150ac72230eb5758ff48b
      #   with:
      #     image: awscli-kubectl
      #     registry: ghcr.io
      #     password: ${{ secrets.GITHUB_TOKEN }}
      #     tag: ${{ github.event.pull_request.head.sha }}

      - name: "Skopeo"
        run: |    
          skopeo copy docker://ghcr.io/stv-io/awscli-kubectl/awscli-kubectl:${{ github.event.pull_request.head.sha }} docker://ghcr.io/stv-io/awscli-kubectl/awscli-kubectl:v0.9.9