name: Test built container

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/stv-io/awscli-kubectl/awscli-kubectl:${{ github.event.pull_request.head.sha }} 
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}

    steps:
      - name: terraform version
        run: terraform version

      - name: kubectl version
        run: kubectl version --output=json
